from caen_libs import caenhvwrapper as hv
from enum import Flag

class _BdStatus_Default(Flag):
    PW_FAIL: int = ...
    FW_CHKERR: int = ...
    HVCAL_ERR: int = ...
    TEMP_ERR: int = ...
    UN_TEMP: int = ...
    OV_TEMP: int = ...

class _BdStatus_N1470(Flag):
    CH0_ALARM: int = ...
    CH1_ALARM: int = ...
    CH2_ALARM: int = ...
    CH3_ALARM: int = ...
    PW_FAIL: int = ...
    OV_POWER: int = ...
    HV_CLK_FAIL: int = ...

class _BdStatus_DT55XXE(Flag):
    ALARMED: int = ...

class _BdStatus_SMARTHV(Flag):
    PW_FAIL: int = ...
    CAL_ERR: int = ...
    INTERLOCK: int = ...
    TEMP_ERR: int = ...

class _ChStatus_Default(Flag):
    ON: int = ...
    UP: int = ...
    DOWN: int = ...
    OVC: int = ...
    OVV: int = ...
    UNV: int = ...
    E_TRIPPED: int = ...
    HV_MAX: int = ...
    EXT_DIS: int = ...
    I_TRIPPED: int = ...
    CAL_ERR: int = ...
    UNPLUGG: int = ...

class _ChStatus_SY4527_SY5527_R6060(Flag):
    ON: int = ...
    UP: int = ...
    DOWN: int = ...
    OVC: int = ...
    OVV: int = ...
    UNV: int = ...
    E_TRIPPED: int = ...
    HV_MAX: int = ...
    EXT_DIS: int = ...
    I_TRIPPED: int = ...
    CAL_ERR: int = ...
    UNPLUGG: int = ...
    UNC: int = ...
    OVV_PROT: int = ...
    PWR_FAIL: int = ...
    TEMP_FAIL: int = ...

class _ChStatus_N1470(Flag):
    ON: int = ...
    UP: int = ...
    DOWN: int = ...
    OVC: int = ...
    OVV: int = ...
    UNV: int = ...
    MAX_V: int = ...
    TRIPPED: int = ...
    OVP: int = ...
    OVT: int = ...
    DISABLED: int = ...
    KILL: int = ...
    INTERLOCK: int = ...
    CAL_ERR: int = ...

class _ChStatus_V65XX(Flag):
    ON: int = ...
    UP: int = ...
    DOWN: int = ...
    OVC: int = ...
    OVV: int = ...
    UNV: int = ...
    I_MAX: int = ...
    HV_MAX: int = ...
    TRIP: int = ...
    OVP: int = ...
    OVT: int = ...
    DISABLED: int = ...
    INTERLOCK: int = ...
    UNCAL: int = ...

class _ChStatus_DT55XXE(Flag):
    ON: int = ...
    UP: int = ...
    DOWN: int = ...
    OVC: int = ...
    OVV: int = ...
    UNV: int = ...
    MAX_V: int = ...
    TRIPPED: int = ...
    MAX_POWER: int = ...
    TEMP_WARN: int = ...
    DISABLED: int = ...
    KILL: int = ...
    INTERLOCK: int = ...
    CAL_ERR: int = ...

class _ChStatus_SMARTHV(Flag):
    ON: int = ...
    UP: int = ...
    DOWN: int = ...
    OVC: int = ...
    OVV: int = ...
    UNV: int = ...
    TRIPPED: int = ...
    OVP: int = ...
    TEMP_WARN: int = ...
    OVT: int = ...
    KILL: int = ...
    INTERLOCK: int = ...
    DISABLED: int = ...
    COMM_FAIL: int = ...
    LOCK: int = ...
    MAX_V: int = ...
    CAL_ERR: int = ...

def decode_bd_status(system_type: hv.SystemType, value: int) -> str: ...
def decode_ch_status(system_type: hv.SystemType, value: int) -> str: ...
